export const FETCH_ATTEMPT = 'course/FETCH_ATTEMPT'
export const FETCH_SUCCESS = 'course/FETCH_SUCCESS'
export const FETCH_ERROR = 'course/FETCH_ERROR'

export const FETCH_HOT_COURSES_ATTEMPT = 'course/FETCH_HOT_COURSES_ATTEMPT'
export const FETCH_HOT_COURSES_SUCCESS = 'course/FETCH_HOT_COURSES_SUCCESS'
export const FETCH_HOT_COURSES_ERROR = 'course/FETCH_HOT_COURSES_ERROR'
