export const FETCH_ATTEMPT = 'course/FETCH_ATTEMPT'
export const FETCH_SUCCESS = 'course/FETCH_SUCCESS'
export const FETCH_ERROR = 'course/FETCH_ERROR'

export const LIKE_COURSE_ATTEMPT = 'course/LIKE_COURSE_ATTEMPT'
export const LIKE_COURSE_SUCCESS = 'course/LIKE_COURSE_SUCCESS'
export const LIKE_COURSE_ERROR = 'course/LIKE_COURSE_ERROR'

export const UNLIKE_COURSE_ATTEMPT = 'course/UNLIKE_COURSE_ATTEMPT'
export const UNLIKE_COURSE_SUCCESS = 'course/UNLIKE_COURSE_SUCCESS'
export const UNLIKE_COURSE_ERROR = 'course/UNLIKE_COURSE_ERROR'

export const FETCH_HOT_COURSES_ATTEMPT = 'course/FETCH_HOT_COURSES_ATTEMPT'
export const FETCH_HOT_COURSES_SUCCESS = 'course/FETCH_HOT_COURSES_SUCCESS'
export const FETCH_HOT_COURSES_ERROR = 'course/FETCH_HOT_COURSES_ERROR'
