export const SWITCH_VIEW = 'prof/SWITCH_VIEW'
export const FETCH_ATTEMPT = 'prof/FETCH_ATTEMPT'
export const FETCH_SUCCESS = 'prof/FETCH_SUCCESS'
export const FETCH_ERROR = 'prof/FETCH_ERROR'

export const FOLLOW_PROF_ATTEMPT = 'prof/FOLLOW_PROF_ATTEMPT'
export const FOLLOW_PROF_SUCCESS = 'prof/FOLLOW_PROF_SUCCESS'
export const FOLLOW_PROF_ERROR = 'prof/FOLLOW_PROF_ERROR'

export const UNFOLLOW_PROF_ATTEMPT = 'prof/UNFOLLOW_PROF_ATTEMPT'
export const UNFOLLOW_PROF_SUCCESS = 'prof/UNFOLLOW_PROF_SUCCESS'
export const UNFOLLOW_PROF_ERROR = 'prof/UNFOLLOW_PROF_ERROR'
