export const FETCH_RANK_LIST_ATTEMPT = 'FETCH_RANK_LIST_ATTEMPT'
export const FETCH_RANK_LIST_SUCCESS = 'FETCH_RANK_LIST_SUCCESS'
export const FETCH_RANK_LIST_ERROR = 'FETCH_RANK_LIST_ERROR'

export const SWITCH_VIEW = 'SWITCH_VIEW'
export const FIRST_PAGE = 'FIRST_PAGE'
