// all reviews
export const FETCH_REVIEWS_ATTEMPT = 'FETCH_REVIEWS_ATTEMPT'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_ERROR = 'FETCH_REVIEWS_ERROR'

// single review
export const FETCH_REVIEW_BY_ID_ATTEMPT = 'FETCH_REVIEW_BY_ID_ATTEMPT'
export const FETCH_REVIEW_BY_ID_SUCCESS = 'FETCH_REVIEW_BY_ID_SUCCESS'
export const FETCH_REVIEW_BY_ID_ERROR = 'FETCH_REVIEW_BY_ID_ERROR'

// review pagination
export const SWITCH_VIEW = 'SWITCH_VIEW'
export const LATEST_NEXT_PAGE = 'NEXT_PAGE_LATEST'
export const LATEST_PREV_PAGE = 'LATEST_PREV_PAGE'

export const FIRST_PAGE = 'FIRST_PAGE'
export const NEXT_PAGE = 'NEXT_PAGE'
export const PREV_PAGE = 'PREV_PAGE'

// add review
export const SUBMIT_ATTEMPT = 'review/SUBMIT_ATTEMPT'
export const SUBMIT_SUCCESS = 'review/SUBMIT_SUCCESS'
export const SUBMIT_ERROR = 'review/SUBMIT_ERROR'

// all hot reviews
export const FETCH_HOT_REVIEWS_ATTEMPT = 'FETCH_HOT_REVIEWS_ATTEMPT'
export const FETCH_HOT_REVIEWS_SUCCESS = 'FETCH_HOT_REVIEWS_SUCCESS'
export const FETCH_HOT_REVIEWS_ERROR = 'FETCH_HOT_REVIEWS_ERROR'

// all new reviews
export const FETCH_NEW_REVIEWS_ATTEMPT = 'FETCH_NEW_REVIEWS_ATTEMPT'
export const FETCH_NEW_REVIEWS_SUCCESS = 'FETCH_NEW_REVIEWS_SUCCESS'
export const FETCH_NEW_REVIEWS_ERROR = 'FETCH_NEW_REVIEWS_ERROR'

// like review
export const LIKE_REVIEW_ATTEMPT = 'LIKE_REVIEW_ATTEMPT'
export const LIKE_REVIEW_SUCCESS = 'LIKE_REVIEW_SUCCESS'
export const LIKE_REVIEW_ERROR = 'LIKE_REVIEW_ERROR'

// unlike review
export const UNLIKE_REVIEW_ATTEMPT = 'UNLIKE_REVIEW_ATTEMPT'
export const UNLIKE_REVIEW_SUCCESS = 'UNLIKE_REVIEW_SUCCESS'
export const UNLIKE_REVIEW_ERROR = 'UNLIKE_REVIEW_ERROR'

// dislike review
export const DISLIKE_REVIEW_ATTEMPT = 'DISLIKE_REVIEW_ATTEMPT'
export const DISLIKE_REVIEW_SUCCESS = 'DISLIKE_REVIEW_SUCCESS'
export const DISLIKE_REVIEW_ERROR = 'DISLIKE_REVIEW_ERROR'

// undislike review
export const UNDISLIKE_REVIEW_ATTEMPT = 'UNDISLIKE_REVIEW_ATTEMPT'
export const UNDISLIKE_REVIEW_SUCCESS = 'UNDISLIKE_REVIEW_SUCCESS'
export const UNDISLIKE_REVIEW_ERROR = 'UNDISLIKE_REVIEW_ERROR'
