// all reviews
export const FETCH_REVIEWS_ATTEMPT = 'FETCH_REVIEWS_ATTEMPT'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_ERROR = 'FETCH_REVIEWS_ERROR'

// single review
export const FETCH_REVIEW_ATTEMPT = 'FETCH_REVIEW_ATTEMPT'
export const FETCH_REVIEW_BY_ID_SUCCESS = 'FETCH_REVIEW_BY_ID_SUCCESS'
export const FETCH_REVIEW_BY_ID_ERROR = 'FETCH_REVIEW_BY_ID_ERROR'
