// all reviews
export const FETCH_REVIEWS_ATTEMPT = 'FETCH_REVIEWS_ATTEMPT'
export const FETCH_REVIEWS_SUCCESS = 'FETCH_REVIEWS_SUCCESS'
export const FETCH_REVIEWS_ERROR = 'FETCH_REVIEWS_ERROR'

// single review
export const FETCH_REVIEW_BY_ID_ATTEMPT = 'FETCH_REVIEW_BY_ID_ATTEMPT'
export const FETCH_REVIEW_BY_ID_SUCCESS = 'FETCH_REVIEW_BY_ID_SUCCESS'
export const FETCH_REVIEW_BY_ID_ERROR = 'FETCH_REVIEW_BY_ID_ERROR'

// review pagination
export const SWITCH_VIEW = 'SWITCH_VIEW'
export const LATEST_NEXT_PAGE = 'NEXT_PAGE_LATEST'
export const LATEST_PREV_PAGE = 'LATEST_PREV_PAGE'

export const FIRST_PAGE = 'FIRST_PAGE'
export const NEXT_PAGE = 'NEXT_PAGE'
export const PREV_PAGE = 'PREV_PAGE'
