export const SET_DISPLAY_VALUE = 'search_course/SET_DISPLAY_VALUE'
export const SELECT_OPTION = 'search_course/SELECT_OPTION'
export const RESET_COMPONENT = 'search_course/RESET_COMPONENT'
export const FETCH_OPTIONS_ATTEMPT = 'search_course/FETCH_OPTIONS_ATTEMPT'
export const FETCH_OPTIONS_SUCCESS = 'search_course/FETCH_OPTIONS_SUCCESS'
export const FETCH_OPTIONS_ERROR = 'search_course/FETCH_OPTIONS_ERROR'
export const SET_COURSE_ID = 'search_course/SET_COURSE_ID'
